version: "3"
#Indicamos la version docker compose que utilizamos

#Y luego los servicios que vamos a implementar
services:

#Aquí indicamos el nombre que queramos
  seguros:
    #Indicamos la carpeta donde guardamos el Docker File
    build: 
      context: .
    #Eliminamos esta línea que se sustituye por el dockerfile
    #image: php:7.0-apache
    container_name: seguros
    volumes:
      #Carpeta donde guardaremos los archivos web : carpeta interna de Docker
      - ./:/var/www/html
    expose:
      #Puerto que queremos exponer a para poder compartirlo con otros contenedores
      - 4600
    ports:
      - "4600:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"